# Generated by Django 5.1.7 on 2025-03-29 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpanel',
            name='admin_user',
            field=models.ForeignKey(on_delete=models.CASCADE, to='auth.User')
        )
    ]
